server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: Suraj@1997
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: HOTEL-SERVICE
  config:
    import: configserver:http://localhost:8088
